Repository TahleeJ/OffshoreWindJobNavigator-1323, pull requests merged in 2022-02, with the labels that each got.

#96 Create typescript types for Firestore objects
  package-lock.json
  package.json
  src/firebase/Types.ts
  src/react components/survey/SurveyAdminister.tsx
  src/react components/survey/SurveyCreator.tsx
Labels: backend

#107 Survey delete popup created
  src/react components/Job/DeletePopup.tsx
  src/react components/survey/DeletePopup.tsx
  src/react components/survey/ListElement.tsx
  src/styling/App.css
  src/styling/App.css.map
  src/styling/App.scss
Labels: enhancement, frontend

#108 Added Job Queries
  src/App.tsx
  src/firebase/Firestore.ts
  src/firebase/JobQueries.ts
  src/firebase/Types.ts
  src/react components/AdminHome.tsx
  src/redux/dataSlice.ts.ts
Labels: backend

#109 Update permissions function with new handling
  functions/index.js
  src/App.tsx
  src/firebase/AdminQueries.ts
  src/firebase/Firebase.ts
Labels: enhancement, backend

#115 Add newUser function to abstract User accesses
  functions/index.js
  src/App.tsx
  src/firebase/Firebase.ts
Labels: enhancement, backend
